SELECT MIN(bebidas.qtd1) AS MINIMO_INGREDIENTE_1, AVG(bebidas.qtd1) AS MEDIA_INGREDIENTE_1, MAX(bebidas.qtd1) AS MAXIMO_INGREDIENTE_1,
MIN(bebidas.qtd2) AS MINIMO_INGREDIENTE_2, AVG(bebidas.qtd2) AS MEDIA_INGREDIENTE_2, MAX(bebidas.qtd2) AS MAXIMO_INGREDIENTE_2
FROM bebidas